from pathlib import Path

p = Path('panel-privado.html')
s = p.read_text(encoding='utf-8')

css_anchor = "  .analysis-note { margin-top:12px; color:var(--ink-soft); font-size:11.5px; line-height:1.5; }\n"
css_add = css_anchor + "  .cleanup-details { margin:16px 0 0; border-top:1px solid var(--panel-line); padding-top:14px; }\n  .cleanup-details summary { list-style:none; cursor:pointer; color:var(--ink-soft); font-size:12px; font-weight:700; width:max-content; }\n  .cleanup-details summary::-webkit-details-marker { display:none; }\n  .cleanup-details summary::after { content:' +'; }\n  .cleanup-details[open] summary::after { content:' −'; }\n  .cleanup-box { margin-top:12px; padding:14px; border:1px solid #ECD2D4; border-radius:12px; background:#FFF9F9; }\n  .cleanup-box p { color:var(--ink-soft); font-size:12px; line-height:1.5; margin:0 0 10px; max-width:760px; }\n  button.action-delete { background:transparent; color:#9A4B50; border-color:transparent; padding:5px 7px; min-height:30px; }\n  button.action-delete:hover { background:var(--danger-bg); color:var(--accent); }\n"
if css_anchor not in s:
    raise SystemExit('css anchor missing')
s = s.replace(css_anchor, css_add, 1)

html_anchor = """        <div class=\"table-scroll orders-scroll\">\n          <table>\n            <thead>\n              <tr><th>Código</th><th>Total</th><th>Cobrado / por cobrar</th><th>Pago</th><th>Tipo</th><th>Creada</th><th>Estado</th><th>Acciones</th></tr>\n            </thead>\n            <tbody id=\"ordersBody\"></tbody>\n          </table>\n        </div>\n      </div>\n    </div>\n\n    <div id=\"viewInventario\""" 
html_repl = """        <div class=\"table-scroll orders-scroll\">\n          <table>\n            <thead>\n              <tr><th>Código</th><th>Total</th><th>Cobrado / por cobrar</th><th>Pago</th><th>Tipo</th><th>Creada</th><th>Estado</th><th>Acciones</th></tr>\n            </thead>\n            <tbody id=\"ordersBody\"></tbody>\n          </table>\n        </div>\n        <details class=\"cleanup-details\">\n          <summary>Datos de prueba</summary>\n          <div class=\"cleanup-box\">\n            <p><strong>Reiniciar solicitudes</strong> elimina el historial de solicitudes y reinicia la numeración a PD-AAAA-0001. El inventario, productos, precios, tallas y colores permanecen exactamente como están.</p>\n            <button class=\"danger-ghost\" id=\"resetPracticeDataBtn\">Reiniciar datos de prueba</button>\n            <div id=\"resetPracticeMsg\" style=\"margin-top:10px;\"></div>\n          </div>\n        </details>\n      </div>\n    </div>\n\n    <div id=\"viewInventario\""" 
if html_anchor not in s:
    raise SystemExit('html anchor missing')
s = s.replace(html_anchor, html_repl, 1)

old_order_actions = """    if (o.status === 'pending') {\n      const confirmLabel = o.payment_mode === 'deposit' ? 'Confirmar abono' : 'Confirmar pago';\n      actions = `<button class=\"action-confirm\" data-action=\"pay\" data-id=\"${o.id}\" data-status=\"${o.status}\" data-payment-mode=\"${o.payment_mode}\">${confirmLabel}</button>\n                 <button class=\"danger\" data-action=\"cancel\" data-id=\"${o.id}\" data-status=\"${o.status}\">Cancelar</button>`;\n    } else if (o.status === 'reserved') {\n      actions = `<button class=\"action-confirm\" data-action=\"pay\" data-id=\"${o.id}\" data-status=\"${o.status}\" data-payment-mode=\"${o.payment_mode}\">Confirmar saldo</button>\n                 <button class=\"danger\" data-action=\"cancel\" data-id=\"${o.id}\" data-status=\"${o.status}\">Cancelar reserva</button>`;\n    }\n"""
new_order_actions = """    if (o.status === 'pending') {\n      const confirmLabel = o.payment_mode === 'deposit' ? 'Confirmar abono' : 'Confirmar pago';\n      actions = `<button class=\"action-confirm\" data-action=\"pay\" data-id=\"${o.id}\" data-code=\"${o.order_number}\" data-status=\"${o.status}\" data-payment-mode=\"${o.payment_mode}\">${confirmLabel}</button>\n                 <button class=\"danger\" data-action=\"cancel\" data-id=\"${o.id}\" data-code=\"${o.order_number}\" data-status=\"${o.status}\">Cancelar</button>`;\n    } else if (o.status === 'reserved') {\n      actions = `<button class=\"action-confirm\" data-action=\"pay\" data-id=\"${o.id}\" data-code=\"${o.order_number}\" data-status=\"${o.status}\" data-payment-mode=\"${o.payment_mode}\">Confirmar saldo</button>\n                 <button class=\"danger\" data-action=\"cancel\" data-id=\"${o.id}\" data-code=\"${o.order_number}\" data-status=\"${o.status}\">Cancelar reserva</button>`;\n    }\n    actions += `<button class=\"action-delete\" data-action=\"delete\" data-id=\"${o.id}\" data-code=\"${o.order_number}\" data-status=\"${o.status}\" title=\"Borra solo el registro; no modifica inventario\">Borrar</button>`;\n"""
if old_order_actions not in s:
    raise SystemExit('order actions anchor missing')
s = s.replace(old_order_actions, new_order_actions, 1)

old_body_handler = """    const currentStatus = btn.dataset.status;\n    if (action === 'cancel') {\n      const warning = currentStatus === 'reserved'\n        ? 'Esta reserva ya tiene un abono confirmado. Al cancelarla se liberará el stock, pero cualquier devolución de dinero debe gestionarse manualmente. ¿Continuar?'\n        : '¿Cancelar esta solicitud?';\n      if (!confirm(warning)) return;\n    }\n    btn.disabled = true;\n\n    const rpcName = action === 'pay' ? 'confirm_order_payment' : 'cancel_order';\n    const { data, error } = await client.rpc(rpcName, { p_order_id: id });\n\n    btn.disabled = false;\n    if (error) { showMsg(ordersMsg, error.message, 'error'); return; }\n    const row = Array.isArray(data) ? data[0] : data;\n    const resultLabel = row.status === 'reserved'\n      ? 'abono confirmado; pieza reservada y stock apartado'\n      : row.status === 'paid'\n        ? 'pago completado'\n        : 'cancelada';\n    showMsg(ordersMsg, `Solicitud ${row.order_number}: ${resultLabel}.`, 'ok');\n    loadOrders(activeStatus);\n    loadFinancialSummary();\n    loadInventory();\n"""
new_body_handler = """    const currentStatus = btn.dataset.status;\n    if (action === 'delete') {\n      const code = btn.dataset.code || 'esta solicitud';\n      if (!confirm(`¿Borrar ${code} del historial?\\n\\nEsto elimina el registro y sus datos de análisis, pero NO modifica el inventario. No se puede deshacer.`)) return;\n      btn.disabled = true;\n      const { data, error } = await client.rpc('delete_order_record_no_stock', { p_order_id: id });\n      btn.disabled = false;\n      if (error) { showMsg(ordersMsg, error.message, 'error'); return; }\n      showMsg(ordersMsg, `${code} eliminado del historial. El inventario no cambió.`, 'ok');\n      loadOrders(activeStatus);\n      loadFinancialSummary();\n      if (viewLoaded.analisis) loadAnalysis();\n      return;\n    }\n    if (action === 'cancel') {\n      const warning = currentStatus === 'reserved'\n        ? 'Esta reserva ya tiene un abono confirmado. Al cancelarla se liberará el stock, pero cualquier devolución de dinero debe gestionarse manualmente. ¿Continuar?'\n        : '¿Cancelar esta solicitud?';\n      if (!confirm(warning)) return;\n    }\n    btn.disabled = true;\n\n    const rpcName = action === 'pay' ? 'confirm_order_payment' : 'cancel_order';\n    const { data, error } = await client.rpc(rpcName, { p_order_id: id });\n\n    btn.disabled = false;\n    if (error) { showMsg(ordersMsg, error.message, 'error'); return; }\n    const row = Array.isArray(data) ? data[0] : data;\n    const resultLabel = row.status === 'reserved'\n      ? 'abono confirmado; pieza reservada y stock apartado'\n      : row.status === 'paid'\n        ? 'pago completado'\n        : 'cancelada';\n    showMsg(ordersMsg, `Solicitud ${row.order_number}: ${resultLabel}.`, 'ok');\n    loadOrders(activeStatus);\n    loadFinancialSummary();\n    loadInventory();\n    if (viewLoaded.analisis) loadAnalysis();\n"""
if old_body_handler not in s:
    raise SystemExit('body handler anchor missing')
s = s.replace(old_body_handler, new_body_handler, 1)

old_search_actions = """    if (order.status === 'pending') {\n      const confirmLabel = order.payment_mode === 'deposit' ? 'Confirmar abono' : 'Confirmar pago';\n      actions = `<div class=\"row\" style=\"margin-top:10px;\">\n        <button class=\"action-confirm\" data-action=\"pay\" data-id=\"${order.id}\" data-status=\"${order.status}\">${confirmLabel}</button>\n        <button class=\"danger\" data-action=\"cancel\" data-id=\"${order.id}\" data-status=\"${order.status}\">Cancelar</button>\n      </div>`;\n    } else if (order.status === 'reserved') {\n      actions = `<div class=\"row\" style=\"margin-top:10px;\">\n        <button class=\"action-confirm\" data-action=\"pay\" data-id=\"${order.id}\" data-status=\"${order.status}\">Confirmar saldo</button>\n        <button class=\"danger\" data-action=\"cancel\" data-id=\"${order.id}\" data-status=\"${order.status}\">Cancelar reserva</button>\n      </div>`;\n    }\n"""
new_search_actions = """    if (order.status === 'pending') {\n      const confirmLabel = order.payment_mode === 'deposit' ? 'Confirmar abono' : 'Confirmar pago';\n      actions = `<div class=\"row\" style=\"margin-top:10px;\">\n        <button class=\"action-confirm\" data-action=\"pay\" data-id=\"${order.id}\" data-code=\"${order.order_number}\" data-status=\"${order.status}\">${confirmLabel}</button>\n        <button class=\"danger\" data-action=\"cancel\" data-id=\"${order.id}\" data-code=\"${order.order_number}\" data-status=\"${order.status}\">Cancelar</button>\n        <button class=\"action-delete\" data-action=\"delete\" data-id=\"${order.id}\" data-code=\"${order.order_number}\" data-status=\"${order.status}\">Borrar</button>\n      </div>`;\n    } else if (order.status === 'reserved') {\n      actions = `<div class=\"row\" style=\"margin-top:10px;\">\n        <button class=\"action-confirm\" data-action=\"pay\" data-id=\"${order.id}\" data-code=\"${order.order_number}\" data-status=\"${order.status}\">Confirmar saldo</button>\n        <button class=\"danger\" data-action=\"cancel\" data-id=\"${order.id}\" data-code=\"${order.order_number}\" data-status=\"${order.status}\">Cancelar reserva</button>\n        <button class=\"action-delete\" data-action=\"delete\" data-id=\"${order.id}\" data-code=\"${order.order_number}\" data-status=\"${order.status}\">Borrar</button>\n      </div>`;\n    } else {\n      actions = `<div class=\"row\" style=\"margin-top:10px;\"><button class=\"action-delete\" data-action=\"delete\" data-id=\"${order.id}\" data-code=\"${order.order_number}\" data-status=\"${order.status}\">Borrar</button></div>`;\n    }\n"""
if old_search_actions not in s:
    raise SystemExit('search actions anchor missing')
s = s.replace(old_search_actions, new_search_actions, 1)

old_search_handler = """        if (btn.dataset.action === 'cancel') {\n          const warning = btn.dataset.status === 'reserved'\n            ? 'Esta reserva tiene un abono confirmado. Se liberará el stock y cualquier devolución de dinero se gestiona manualmente. ¿Continuar?'\n            : '¿Cancelar esta solicitud?';\n          if (!confirm(warning)) return;\n        }\n        const rpcName = btn.dataset.action === 'pay' ? 'confirm_order_payment' : 'cancel_order';\n        const { data, error } = await client.rpc(rpcName, { p_order_id: btn.dataset.id });\n        if (error) { resultEl.innerHTML += `<p class=\"msg msg-error\">${error.message}</p>`; return; }\n        document.getElementById('searchBtn').click();\n        loadOrders(activeStatus);\n        loadInventory();\n"""
new_search_handler = """        if (btn.dataset.action === 'delete') {\n          const code = btn.dataset.code || order.order_number;\n          if (!confirm(`¿Borrar ${code} del historial?\\n\\nEl inventario no se modificará.`)) return;\n          const { error } = await client.rpc('delete_order_record_no_stock', { p_order_id: btn.dataset.id });\n          if (error) { resultEl.innerHTML += `<p class=\"msg msg-error\">${error.message}</p>`; return; }\n          resultEl.innerHTML = '<p class=\"msg msg-ok\">Solicitud eliminada. El inventario no cambió.</p>';\n          loadOrders(activeStatus);\n          loadFinancialSummary();\n          if (viewLoaded.analisis) loadAnalysis();\n          return;\n        }\n        if (btn.dataset.action === 'cancel') {\n          const warning = btn.dataset.status === 'reserved'\n            ? 'Esta reserva tiene un abono confirmado. Se liberará el stock y cualquier devolución de dinero se gestiona manualmente. ¿Continuar?'\n            : '¿Cancelar esta solicitud?';\n          if (!confirm(warning)) return;\n        }\n        const rpcName = btn.dataset.action === 'pay' ? 'confirm_order_payment' : 'cancel_order';\n        const { data, error } = await client.rpc(rpcName, { p_order_id: btn.dataset.id });\n        if (error) { resultEl.innerHTML += `<p class=\"msg msg-error\">${error.message}</p>`; return; }\n        document.getElementById('searchBtn').click();\n        loadOrders(activeStatus);\n        loadFinancialSummary();\n        loadInventory();\n        if (viewLoaded.analisis) loadAnalysis();\n"""
if old_search_handler not in s:
    raise SystemExit('search handler anchor missing')
s = s.replace(old_search_handler, new_search_handler, 1)

reset_anchor = "  document.getElementById('analysisWindow').addEventListener('change', loadAnalysis);\n\n  // ---- Inventario ----\n"
reset_code = """  document.getElementById('analysisWindow').addEventListener('change', loadAnalysis);\n\n  const resetPracticeDataBtn = document.getElementById('resetPracticeDataBtn');\n  if (resetPracticeDataBtn) {\n    resetPracticeDataBtn.addEventListener('click', async () => {\n      const msgEl = document.getElementById('resetPracticeMsg');\n      const ok = confirm('Esto borrará TODAS las solicitudes de prueba y reiniciará la numeración.\\n\\nEl inventario, productos, precios, tallas y colores NO se modificarán. ¿Continuar?');\n      if (!ok) return;\n      const typed = prompt('Para confirmar, escribe BORRAR');\n      if (typed !== 'BORRAR') {\n        showMsg(msgEl, 'No se realizó ningún cambio.', 'error');\n        return;\n      }\n      resetPracticeDataBtn.disabled = true;\n      const { data, error } = await client.rpc('reset_practice_orders_no_stock');\n      resetPracticeDataBtn.disabled = false;\n      if (error) { showMsg(msgEl, error.message, 'error'); return; }\n      const row = Array.isArray(data) ? data[0] : data;\n      showMsg(msgEl, `${row?.deleted_orders ?? 0} solicitudes eliminadas. La próxima solicitud será ${row?.next_order_number || 'PD-AAAA-0001'}. El inventario quedó intacto.`, 'ok');\n      document.getElementById('searchResult').innerHTML = '';\n      loadOrders(activeStatus);\n      loadFinancialSummary();\n      if (viewLoaded.analisis) loadAnalysis();\n    });\n  }\n\n  // ---- Inventario ----\n"""
if reset_anchor not in s:
    raise SystemExit('reset anchor missing')
s = s.replace(reset_anchor, reset_code, 1)

p.write_text(s, encoding='utf-8')
print('patched practice cleanup controls')
